feat: add support for WAR_PATH env var
Add support for a new `WAR_PATH` environment variable that allows users to
specify where the .war file too run is stored. This is useful when the .war
file is not stored at the root of the application.

Also downloads JVM common tools to cache, and use the cached version if
it's available.

Also updates the default values for:
- `JAVA_VERSION`: from `1.8` to `17`
- `WEBAPP_RUNNER_VERSION`: from `8.5.11.3` to `9.0.52.1`

I'm also suggesting to rename `WEBAPP_RUNNER_VERSION` to
`JAVA_WEBAPP_RUNNER_VERSION`. The code still supports
`WEBAPP_RUNNER_VERSION`.

The README file has been updated consequently.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,38 +1,101 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
-# fail fast
-set -e
+set -eo pipefail
 
-if [[ -n "$BUILDPACK_DEBUG" ]]; then
-  set -x
+if [[ -n "${BUILDPACK_DEBUG}" ]]
+then
+    set -x
 fi
 
-BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
-. $BP_DIR/lib/common.sh
+readonly build_dir="${1}"
+readonly cache_dir="${2}"
+env_dir="${3}"
 
-# parse args
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
+readonly java_version="${JAVA_VERSION:-17}"
+readonly webapp_runner_version="${JAVA_WEBAPP_RUNNER_VERSION:-${WEBAPP_RUNNER_VERSION:-9.0.52.1}}"
 
-export_env_dir $ENV_DIR
+readonly base_dir="$( cd -P "$( dirname "$0" )" && pwd )"
+readonly buildpack_dir="$( readlink -f "${base_dir}/.." )"
 
-# Install Java
-JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-"https://buildpacks-repository.s3.eu-central-1.amazonaws.com/jvm-common.tar.xz"}
-mkdir -p /tmp/jvm-common
-curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK | tar xJm -C /tmp/jvm-common --strip-components=1
-. /tmp/jvm-common/bin/util
-. /tmp/jvm-common/bin/java
 
-if [[ -n "${JAVA_VERSION}" ]]; then
-  echo "java.runtime.version=${JAVA_VERSION}" > ${BUILD_DIR}/system.properties
-fi
-install_java_with_overlay ${BUILD_DIR}
+source "${buildpack_dir}/lib/common.sh"
 
-# Install Webapp Runner
-WEBAPP_RUNNER_VERSION=${WEBAPP_RUNNER_VERSION:-8.5.11.3}
-WEBAPP_RUNNER_URL="https://buildpacks-repository.s3.eu-central-1.amazonaws.com/webapp-runner-${WEBAPP_RUNNER_VERSION}.jar"
-curl --retry 3 --silent --location $WEBAPP_RUNNER_URL --output ${BUILD_DIR}/webapp-runner.jar
+export_env_dir "${env_dir}"
 
-mkdir -p $CACHE_DIR
+
+# Installs Java and webapp_runner
+#
+# Usage: install_webapp_runner <build_dir> <cache_dir> <java_version> <webapp_runner_version>
+#
+install_webapp_runner() {
+    local jvm_url
+    local runner_url
+
+    local build_d
+    local cache_d
+
+    local tmp_d
+    local jre_version
+    local runner_version
+
+    local cached_jvm_common
+    local cached_runner
+
+    build_d="${1}"
+    cache_d="${2}"
+    jre_version="${3}"
+    runner_version="${4}"
+
+    jvm_url="${JVM_COMMON_BUILDPACK:-"https://buildpacks-repository.s3.eu-central-1.amazonaws.com/jvm-common.tar.xz"}"
+    runner_url="https://buildpacks-repository.s3.eu-central-1.amazonaws.com/webapp-runner-${runner_version}.jar"
+
+    # Install JVM common tools:
+    cached_jvm_common="${cache_d}/jvm-common.tar.xz"
+
+    if [ ! -f "${cached_jvm_common}" ]
+    then
+        curl --location --silent --retry 6 --retry-connrefused --retry-delay 0 \
+            "${jvm_url}" \
+            --output "${cached_jvm_common}"
+    fi
+
+    tmp_d=$( mktemp -d jvm-common-XXXXXX ) && {
+        tar --extract --xz --touch --strip-components=1 \
+            --file "${cached_jvm_common}" \
+            --directory "${tmp_d}"
+
+        # Source utilities and functions:
+        source "${tmp_d}/bin/util"
+        source "${tmp_d}/bin/java"
+
+        echo "java.runtime.version=${jre_version}" \
+            > "${build_d}/system.properties"
+
+        install_java_with_overlay "${build_d}"
+
+        rm -Rf "${tmp_d}"
+    }
+
+    # Install Webapp Runner
+    cached_runner="${cache_d}/webapp-runner-${runner_version}.jar"
+
+    if [ ! -f "${cached_runner}" ]
+    then
+        curl --location --silent --retry 6 --retry-connrefused --retry-delay 0 \
+            "${runner_url}" \
+            --output "${cached_runner}" \
+            || {
+                echo "Unable to download webapp runner ${runner_version}. Aborting."
+                exit 1
+            }
+    fi
+
+    cp "${cached_runner}" "${build_d}/webapp-runner.jar"
+}
+
+readonly -f install_webapp_runner
+
+
+install_webapp_runner "${build_dir}" "${cache_dir}" \
+    "${java_version}" "${webapp_runner_version}"
